-- Generated by the Kristal Cutscene Editor.
-- Source: scripts/world/cutscenes/new_cutscene_2.kcutscene.json
-- Manual changes may be overwritten.

return function(cutscene, ...)
    local vars = {}
    local objects = {}

    local spawned = cutscene:spawnNPC("starwalker", 660, 260, {  })
    cutscene:wait(cutscene:walkTo(spawned, 320, 240, 4, "down", false, "linear"))
    cutscene:wait(cutscene:text("* im the original              starwalker"))
end
