-- Generated by the Kristal Wave Editor.
-- Source: scripts/battle/waves/wave_editor_showcase.kwave.json
-- Manual changes may be overwritten.

local WaveEditorShowcase, super = Class(Wave)
WaveEditorShowcase.id = "wave_editor_showcase"

function WaveEditorShowcase:init()
    super.init(self)
    self.time = 6
    self.arena_x = 320
    self.arena_y = 255
    self.arena_width = 300
    self.arena_height = 180
    self.arena_rotation = 0
    self.soul_start_x = 320
    self.soul_start_y = 255
end

function WaveEditorShowcase:onStart()
    local vars = { bullet_speed = 4 }

    self.wave_objects = {}

    -- Moving Bar
    local moving_bar = self:spawnObject(Solid(true, 220, 205, 72, 14))
    self.wave_objects.moving_bar = moving_bar
    self.timer:after(6, function()
        if moving_bar.parent then moving_bar:remove() end
        self.wave_objects.moving_bar = nil
    end)

    -- Left Bullet
    self.timer:after(0.25, function()
        local left_bullet = self:spawnBullet("smallbullet", 170, 255, 0, 2)
        self.wave_objects.left_bullet = left_bullet
        self.timer:after(3.42, function()
            if left_bullet.parent then left_bullet:remove() end
            self.wave_objects.left_bullet = nil
        end)
    end)

    -- Right Bullet
    self.timer:after(0.25, function()
        local right_bullet = self:spawnBullet("smallbullet", 470, 285, math.pi, 2)
        right_bullet.rotation = math.pi
        self.wave_objects.right_bullet = right_bullet
        self.timer:after(5.25, function()
            if right_bullet.parent then right_bullet:remove() end
            self.wave_objects.right_bullet = nil
        end)
    end)

    self.timer:script(function(wait)
        -- Fire a short random stream from the right side.
        local repeat_count = 8
        for index = 1, repeat_count do
            self:spawnBullet("smallbullet", 500, MathUtils.random(200, 310), math.pi, vars.bullet_speed)
            if index < repeat_count then wait(0.55) end
        end
    end)
end

local function sampleTrack(points, time)
    if #points == 0 then return nil end
    if time <= points[1][1] then return points[1][2] end
    if time >= points[#points][1] then return points[#points][2] end
    for index = 1, #points - 1 do
        local first, second = points[index], points[index + 1]
        if time >= first[1] and time <= second[1] then
            if type(first[2]) ~= "number" or type(second[2]) ~= "number" then return first[2] end
            local amount = (time - first[1]) / math.max(0.000001, second[1] - first[1])
            return MathUtils.lerp(first[2], second[2], amount)
        end
    end
end

function WaveEditorShowcase:update()
    super.update(self)
    local time = Game.battle and Game.battle.wave_timer or 0

    -- Moving Bar X
    local moving_bar_x_target = self.wave_objects.moving_bar
    if moving_bar_x_target then
        moving_bar_x_target.x = sampleTrack({
            { 0, 220 },
            { 3, 348 },
            { 6, 220 },
        }, time)
    end

    -- Arena Rotation
    local arena_rotation_target = Game.battle.arena
    if arena_rotation_target then
        arena_rotation_target.rotation = sampleTrack({
            { 0, 0 },
            { 3, 0.08 },
            { 6, 0 },
        }, time)
    end
end

return WaveEditorShowcase
