return function(cutscene)
    local ralsei = cutscene:slide("party/ralsei/dark/blunt")
    ralsei:setScale(6, 6)
    ralsei.x = 80
    cutscene:setSpeed(1/3)
    cutscene:text("ralsei smoking is BAD\n         :(", "left")
    cutscene:wait(120/30)
    cutscene:removeText()
    cutscene:setSpeed(3/3)
    cutscene:removeSlides()
    cutscene:text("llung canceur......................", "far_left")
    cutscene:wait(120/30)
    cutscene:text("[image:party/susie/dark/t_pose]", "left")
    cutscene:wait(30/30)
    cutscene:removeText()
    cutscene:setSpeed(1/3)
    cutscene:text("kris hit the gangnam style    NOW", "far_left")
    --cutscene:musicWait(14)
    cutscene:wait(1)
end