BattleScene.text("* Susie cooked up a cure!")
BattleScene.text("* What, you want me to cook\nsomething?", "face_2", "susie")
BattleScene.text("* Susie put a hot dog in the\nmicrowave!")
local susie = BattleScene.getCharacter("susie")
local target = BattleScene.getTarget()
target:explode(0, 0, true)
target:hurt(target.health * 0.75, susie)
BattleScene.text("* She forgot to poke holes in it!\nThe hot dog exploded!")
-- Note: the following isn't part of the original act, it's here for testing battle cutscenes!
BattleScene.enemyText(target, "Dumbass")
BattleScene.text("* I, uh, meant to do that.", "face_3", "susie")